##################################
#
# ANSIBLE DEPLOYMENT SCRIPT
# Upgrade only listed packages  
# 
# By Johan Chassaing
#
##################################

##################
#
# How to:
#   ansible-playbook -i <hosts-file> package_upgrade_list.yml
# 
# Dependencies
#   - packages.yml , the list of packages allowed to be upgraded
#
#################

- hosts: all

  # for root
  user: root

  # for specific user
  #user: vagrant
  #sudo: yes

  tasks:
    - include_vars: "packages.yml"

    - name: Update packages list
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

    - name: List packages to upgrade
      shell: aptitude -q -F%p --disable-columns search "~U"
      register: updates
      when: ansible_os_family == 'Debian'

    - name: Upgrade
      apt: name={{ item }} state=latest
      with_items: updates.stdout_lines | intersect(to_upgrade)
      when: ansible_os_family == 'Debian'

