hostname: "{{ inventory_hostname_short }}"
fqdn: "{{ inventory_hostname }}"
# for hosts file
hostname_hosts:
  - 127.0.0.1 {{'\t'}} {{ fqdn }} {{ hostname }} localhost
  - ::1 {{'\t'}}{{'\t'}} localhost ip6-localhost ip6-loopback
  - fe00::0 {{'\t'}} ip6-localnet
  - ff00::0 {{'\t'}} ip6-mcastprefix
  - ff02::1 {{'\t'}} ip6-allnodes
  - ff02::2 {{'\t'}} ip6-allrouters
